### ISSUE TITLE
Installing with r2modman mod manager disables other mods.

### ISSUE THREAD

**Issue by Stalkanbro** [tueman/ValheimMods#1]
Although I'm not sure, I suspect the reason is that the dependency is marked as being https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full/ while most other mods use https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/ and they conflict with each other.

**Comment by tueman** [comment]
Do you recommend I change the dependency or keep it that way? The full pack is newer so I figured most mods would migrate to it.

**Comment by Stalkanbro** [comment]
Well, I can only speak as a basic user with no programming knowledge. As I can't even tell what the difference is between the two packs I'd guess that most people like me would just grab whatever is more popular.

**Comment by tueman** [comment]
I spoke with the Thunderstore devs about the issue and it turns out they're currently working on a solution to match the dependency strings. In the meantime I'll switch it to the more commonly used pack.
