### ISSUE TITLE
Use river max height and extreme max length

### ISSUE THREAD

**Issue by 1010101110** [tueman/ValheimMods#7]
you already have these config settings but don't seem to be using them?

https://github.com/tueman/ValheimMods/blob/main/WorldGenOptions/WorldGenOptions/Generator.cs#L151

* change 0.4f (max height)

https://github.com/tueman/ValheimMods/blob/main/WorldGenOptions/WorldGenOptions/Generator.cs#L154

* change 0.4f (max height) 
* change 5000f (extreme max length)

**Comment by tueman** [comment]
Good catch! Fixed it right up, will be in the next update. Thanks for the report.
